import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '../config/supabase';
import { useAuth } from '../contexts/AuthContext';
import { Home, ArrowLeft } from 'lucide-react';
import { generateLogoConcepts } from '../services/openai';
import { downloadBrandGuide } from '../utils/brandGuide';

import BrandProgress from '../components/brand-identity/BrandProgress';
import StepTransition from '../components/brand-identity/StepTransition';
import StepBusinessName from '../components/brand-identity/StepBusinessName';
import StepPersonality from '../components/brand-identity/StepPersonality';
import StepColorPalette from '../components/brand-identity/StepColorPalette';
import StepLogoGeneration from '../components/brand-identity/StepLogoGeneration';
import StepBrandReveal from '../components/brand-identity/StepBrandReveal';

interface NameOption {
  name: string;
  reason: string;
  vibe: string;
}

interface PaletteOption {
  paletteName: string;
  mood: string;
  primary: string;
  secondary: string;
  accent: string;
}

interface LogoConcept {
  name: string;
  description: string;
  imageUrl: string;
  prompt: string;
}

interface BrandState {
  id: string;
  businessDescription: string;
  names: NameOption[];
  selectedName: string | null;
  personality: string[];
  palettes: PaletteOption[];
  selectedPaletteIndex: number | null;
  logoConcepts: LogoConcept[];
  selectedLogo: LogoConcept | null;
  uploadedLogoUrl: string | null;
  tagline: string | null;
  completedSteps: string[];
}

const STEP_LABELS = ['Name', 'Personality', 'Colors', 'Logo', 'Reveal'];
const STEP_KEYS = ['name', 'personality', 'colors', 'logo', 'reveal'];

function determineInitialStep(brand: BrandState): number {
  if (!brand.selectedName) return 0;
  if (brand.personality.length === 0) return 1;
  if (brand.selectedPaletteIndex === null) return 2;
  if (!brand.selectedLogo && !brand.uploadedLogoUrl) return 3;
  return 4;
}

export default function BrandIdentity() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { currentUser } = useAuth();
  const ideaKey = searchParams.get('ideaKey') || '';

  const [brand, setBrand] = useState<BrandState | null>(null);
  const [businessIdea, setBusinessIdea] = useState<{ name: string; description: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [currentStep, setCurrentStep] = useState(0);
  const [direction, setDirection] = useState<'forward' | 'backward'>('forward');

  const [generatingNames, setGeneratingNames] = useState(false);
  const [generatingPalettes, setGeneratingPalettes] = useState(false);
  const [generatingLogos, setGeneratingLogos] = useState(false);
  const [generatingTagline, setGeneratingTagline] = useState(false);
  const [generatingGuide, setGeneratingGuide] = useState(false);
  const [uploadingLogo, setUploadingLogo] = useState(false);

  const [customName, setCustomName] = useState('');
  const [showLeaveConfirm, setShowLeaveConfirm] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const autoGeneratedPalettes = useRef(false);
  const autoGeneratedLogos = useRef(false);
  const autoGeneratedTagline = useRef(false);

  useEffect(() => {
    if (!currentUser || !ideaKey) {
      setLoading(false);
      return;
    }
    loadData();
  }, [currentUser, ideaKey]);

  const loadData = async () => {
    if (!currentUser || !ideaKey) return;

    try {
      const [brandResult, ideaResult] = await Promise.all([
        supabase.from('brand_identity').select('*').eq('user_id', currentUser.id).eq('idea_key', ideaKey).maybeSingle(),
        supabase.from('business_ideas').select('name, description').eq('user_id', currentUser.id).eq('idea_id', ideaKey).maybeSingle(),
      ]);

      if (ideaResult.data) {
        setBusinessIdea({ name: ideaResult.data.name, description: ideaResult.data.description });
      }

      if (brandResult.error) throw brandResult.error;

      let data = brandResult.data;
      if (!data) {
        const { data: newData, error: insertError } = await supabase
          .from('brand_identity')
          .insert({ user_id: currentUser.id, idea_key: ideaKey })
          .select()
          .single();

        if (insertError) {
          if (insertError.code === '23505') {
            const { data: retryData } = await supabase
              .from('brand_identity').select('*').eq('user_id', currentUser.id).eq('idea_key', ideaKey).maybeSingle();
            data = retryData;
          } else {
            throw insertError;
          }
        } else {
          data = newData;
        }
      }

      if (!data) throw new Error('Failed to load brand identity');

      const normalizedNames = normalizeNames(data.business_names);
      const normalizedPalettes = normalizePalettes(data.color_palettes || data.brand_colors?.palettes);
      const personality: string[] = Array.isArray(data.brand_personality) ? data.brand_personality : [];

      const brandState: BrandState = {
        id: data.id,
        businessDescription: data.offer_description || '',
        names: normalizedNames,
        selectedName: data.selected_name || null,
        personality,
        palettes: normalizedPalettes,
        selectedPaletteIndex: data.brand_colors?.selected_palette_index ?? null,
        logoConcepts: data.logo_data?.concepts || [],
        selectedLogo: data.logo_data?.selected || null,
        uploadedLogoUrl: data.logo_data?.uploaded_logo_url || null,
        tagline: data.selected_tagline || null,
        completedSteps: data.completed_steps || [],
      };

      setBrand(brandState);
      setCurrentStep(determineInitialStep(brandState));
    } catch (err: any) {
      console.error('Error loading brand identity:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const normalizeNames = (raw: any): NameOption[] => {
    if (!raw || !Array.isArray(raw)) return [];
    return raw.map((n: any) => {
      if (typeof n === 'string') return { name: n, reason: 'Generated name', vibe: 'Professional' };
      return { name: n.name, reason: n.reason || n.tagline || '', vibe: n.vibe || 'Professional' };
    });
  };

  const normalizePalettes = (raw: any): PaletteOption[] => {
    if (!raw || !Array.isArray(raw)) return [];
    return raw.map((p: any) => ({
      paletteName: p.paletteName || p.name || 'Custom',
      mood: p.mood || p.description || '',
      primary: p.primary,
      secondary: p.secondary,
      accent: p.accent,
    }));
  };

  const saveToDb = useCallback(async (updates: Record<string, any>) => {
    if (!brand) return;
    try {
      await supabase
        .from('brand_identity')
        .update({ ...updates, updated_at: new Date().toISOString() })
        .eq('id', brand.id);
    } catch (err) {
      console.error('Error saving to DB:', err);
    }
  }, [brand]);

  const goForward = () => {
    setDirection('forward');
    setCurrentStep((s) => Math.min(s + 1, 4));
  };

  const goBack = () => {
    if (currentStep === 0) {
      setShowLeaveConfirm(true);
      return;
    }
    setDirection('backward');
    setCurrentStep((s) => Math.max(s - 1, 0));
  };

  const handleGenerateNames = async () => {
    if (!brand || !brand.businessDescription.trim()) return;
    setGeneratingNames(true);
    try {
      const { data: sessionData } = await supabase.auth.getSession();
      const token = sessionData.session?.access_token;
      const idea = businessIdea
        ? `${businessIdea.name}: ${businessIdea.description}. Additional: ${brand.businessDescription}`
        : brand.businessDescription;

      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/business-name`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          idea,
          ideaKey,
          userId: currentUser?.id,
        }),
      });

      if (!response.ok) throw new Error('Failed to generate names');
      const result = await response.json();
      const rawNames = result.names || [];

      const names: NameOption[] = rawNames.map((n: any) => ({
        name: n.name,
        reason: n.reason || '',
        vibe: n.vibe || guessVibe(n.reason || ''),
      }));

      const newSteps = addStep(brand.completedSteps, 'generate-names');
      setBrand({ ...brand, names, completedSteps: newSteps });
      await saveToDb({
        business_names: names,
        offer_description: brand.businessDescription,
        completed_steps: newSteps,
      });
    } catch (err: any) {
      console.error('Error generating names:', err);
    } finally {
      setGeneratingNames(false);
    }
  };

  const handleSelectName = async (name: string) => {
    if (!brand) return;
    const newSteps = addStep(brand.completedSteps, 'generate-names');
    const updated = { ...brand, selectedName: name, completedSteps: newSteps };
    setBrand(updated);
    await saveToDb({ selected_name: name, completed_steps: newSteps });
  };

  const handleUseCustomName = async () => {
    if (!brand || !customName.trim()) return;
    const name = customName.trim();
    const newNames = [...brand.names, { name, reason: 'Custom name', vibe: 'Professional' as const }];
    const newSteps = addStep(brand.completedSteps, 'generate-names');
    setBrand({ ...brand, names: newNames, selectedName: name, completedSteps: newSteps });
    setCustomName('');
    await saveToDb({
      business_names: newNames,
      selected_name: name,
      completed_steps: newSteps,
    });
  };

  const handleTogglePersonality = async (label: string) => {
    if (!brand) return;
    let updated: string[];
    if (brand.personality.includes(label)) {
      updated = brand.personality.filter((p) => p !== label);
    } else if (brand.personality.length < 2) {
      updated = [...brand.personality, label];
    } else {
      return;
    }
    setBrand({ ...brand, personality: updated });
    await saveToDb({ brand_personality: updated });
  };

  const handlePersonalityNext = async () => {
    if (!brand) return;
    autoGeneratedPalettes.current = false;
    goForward();
  };

  useEffect(() => {
    if (currentStep === 2 && brand && brand.palettes.length === 0 && !generatingPalettes && !autoGeneratedPalettes.current) {
      autoGeneratedPalettes.current = true;
      handleGeneratePalettes();
    }
  }, [currentStep, brand?.palettes.length]);

  const handleGeneratePalettes = async () => {
    if (!brand) return;
    setGeneratingPalettes(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-color-palettes`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          businessName: brand.selectedName,
          industry: businessIdea?.description || 'general business',
          personality: brand.personality,
        }),
      });

      if (!response.ok) throw new Error('Failed to generate palettes');
      const result = await response.json();
      const palettes: PaletteOption[] = result.palettes || [];

      setBrand((prev) => prev ? { ...prev, palettes } : null);
      await saveToDb({ color_palettes: palettes });
    } catch (err) {
      console.error('Error generating palettes:', err);
    } finally {
      setGeneratingPalettes(false);
    }
  };

  const handleSelectPalette = async (index: number) => {
    if (!brand || !brand.palettes[index]) return;
    const palette = brand.palettes[index];
    const newSteps = addStep(brand.completedSteps, 'select-colors');
    const brandColors = {
      primary: palette.primary,
      secondary: palette.secondary,
      accent: palette.accent,
      palettes: brand.palettes,
      selected_palette_index: index,
    };
    setBrand({ ...brand, selectedPaletteIndex: index, completedSteps: newSteps });
    await saveToDb({ brand_colors: brandColors, completed_steps: newSteps });
  };

  const handleCustomizeColor = async (field: 'primary' | 'secondary' | 'accent', value: string) => {
    if (!brand || brand.selectedPaletteIndex === null) return;
    const updatedPalettes = [...brand.palettes];
    updatedPalettes[brand.selectedPaletteIndex] = { ...updatedPalettes[brand.selectedPaletteIndex], [field]: value };
    const palette = updatedPalettes[brand.selectedPaletteIndex];
    const brandColors = {
      primary: palette.primary,
      secondary: palette.secondary,
      accent: palette.accent,
      palettes: updatedPalettes,
      selected_palette_index: brand.selectedPaletteIndex,
    };
    setBrand({ ...brand, palettes: updatedPalettes });
    await saveToDb({ color_palettes: updatedPalettes, brand_colors: brandColors });
  };

  useEffect(() => {
    if (currentStep === 3 && brand && brand.logoConcepts.length === 0 && !generatingLogos && !autoGeneratedLogos.current && brand.selectedName && brand.selectedPaletteIndex !== null) {
      autoGeneratedLogos.current = true;
      handleGenerateLogos();
    }
  }, [currentStep, brand?.logoConcepts.length, brand?.selectedPaletteIndex]);

  const handleGenerateLogos = async (customDirection?: string) => {
    if (!brand || !brand.selectedName || brand.selectedPaletteIndex === null) return;
    setGeneratingLogos(true);
    try {
      const palette = brand.palettes[brand.selectedPaletteIndex];
      const concepts = await generateLogoConcepts(
        brand.selectedName,
        businessIdea?.description || 'general business',
        { primary: palette.primary, secondary: palette.secondary, accent: palette.accent },
        brand.businessDescription || businessIdea?.description,
        brand.personality.join(', '),
        undefined,
        customDirection,
      );

      const newSteps = addStep(brand.completedSteps, 'generate-logo');
      setBrand((prev) => prev ? { ...prev, logoConcepts: concepts, completedSteps: newSteps } : null);
      await saveToDb({
        logo_data: { concepts, selected: brand.selectedLogo },
        completed_steps: newSteps,
      });
    } catch (err) {
      console.error('Error generating logos:', err);
    } finally {
      setGeneratingLogos(false);
    }
  };

  const handleSelectLogo = async (logo: LogoConcept) => {
    if (!brand) return;
    setBrand({ ...brand, selectedLogo: logo, uploadedLogoUrl: null });
    await saveToDb({
      logo_data: { concepts: brand.logoConcepts, selected: logo, uploaded_logo_url: null },
    });
  };

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !currentUser || !brand) return;
    if (!file.type.startsWith('image/')) return;
    if (file.size > 5 * 1024 * 1024) return;

    setUploadingLogo(true);
    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${currentUser.id}/${ideaKey}/custom-logo-${Date.now()}.${fileExt}`;
      const { error: uploadError } = await supabase.storage.from('logos').upload(fileName, file, { upsert: true });
      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage.from('logos').getPublicUrl(fileName);
      setBrand({ ...brand, uploadedLogoUrl: publicUrl, selectedLogo: null });
      await saveToDb({
        logo_data: { concepts: brand.logoConcepts, selected: null, uploaded_logo_url: publicUrl },
      });
    } catch (err) {
      console.error('Error uploading logo:', err);
    } finally {
      setUploadingLogo(false);
    }
  };

  const handleRemoveUpload = async () => {
    if (!brand) return;
    setBrand({ ...brand, uploadedLogoUrl: null });
    await saveToDb({
      logo_data: { concepts: brand.logoConcepts, selected: brand.selectedLogo, uploaded_logo_url: null },
    });
  };

  useEffect(() => {
    if (currentStep === 4 && brand && !brand.tagline && !generatingTagline && !autoGeneratedTagline.current && brand.selectedName) {
      autoGeneratedTagline.current = true;
      handleGenerateTagline();
    }
  }, [currentStep, brand?.tagline]);

  const handleGenerateTagline = async () => {
    if (!brand?.selectedName) return;
    setGeneratingTagline(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-tagline`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          businessName: brand.selectedName,
          businessDescription: brand.businessDescription || businessIdea?.description || '',
          brandPersonality: brand.personality.join(', '),
        }),
      });

      if (!response.ok) throw new Error('Failed to generate tagline');
      const result = await response.json();
      setBrand((prev) => prev ? { ...prev, tagline: result.tagline } : null);
      await saveToDb({ selected_tagline: result.tagline });
    } catch (err) {
      console.error('Error generating tagline:', err);
    } finally {
      setGeneratingTagline(false);
    }
  };

  const handleDownloadGuide = async () => {
    if (!brand?.selectedName) return;
    const logoUrl = brand.uploadedLogoUrl || brand.selectedLogo?.imageUrl;
    if (!logoUrl) return;

    setGeneratingGuide(true);
    try {
      const palette = brand.selectedPaletteIndex !== null ? brand.palettes[brand.selectedPaletteIndex] : null;
      downloadBrandGuide({
        businessName: brand.selectedName,
        slogan: brand.tagline || `Elevating ${brand.selectedName}`,
        logoUrl,
        colors: {
          primary: palette?.primary || '#2979FF',
          secondary: palette?.secondary || '#0A192F',
          accent: palette?.accent || '#06D6A0',
        },
        businessDescription: brand.businessDescription || businessIdea?.description,
        brandPersonality: brand.personality.join(', '),
      });
    } catch (err) {
      console.error('Error downloading guide:', err);
    } finally {
      setGeneratingGuide(false);
    }
  };

  const handleContinueToMessaging = () => {
    navigate(`/storybrand-roadmap?ideaKey=${ideaKey}`);
  };

  const addStep = (steps: string[], step: string): string[] => {
    return steps.includes(step) ? steps : [...steps, step];
  };

  const guessVibe = (reason: string): string => {
    const lower = reason.toLowerCase();
    if (lower.includes('bold') || lower.includes('strong') || lower.includes('power')) return 'Bold';
    if (lower.includes('friend') || lower.includes('warm') || lower.includes('approach')) return 'Friendly';
    if (lower.includes('premium') || lower.includes('luxury') || lower.includes('elegant')) return 'Premium';
    if (lower.includes('clever') || lower.includes('creative') || lower.includes('play')) return 'Clever';
    return 'Professional';
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#0A192F] via-[#0F2847] to-[#0A192F] flex items-center justify-center">
        <div className="text-center">
          <div className="inline-block h-10 w-10 animate-spin rounded-full border-4 border-solid border-[#2979FF] border-r-transparent mb-4" />
          <p className="text-gray-400">Loading your brand studio...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#0A192F] via-[#0F2847] to-[#0A192F] flex items-center justify-center p-8">
        <div className="max-w-lg text-center">
          <div className="text-red-400 text-xl mb-4">Failed to load data</div>
          <div className="text-gray-400 mb-6">{error}</div>
          <button
            onClick={() => navigate('/dashboard')}
            className="px-6 py-3 bg-white/10 border border-white/20 text-white rounded-lg hover:bg-white/20 transition-colors"
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  if (!brand) return null;

  const logoUrl = brand.uploadedLogoUrl || brand.selectedLogo?.imageUrl || '';
  const palette = brand.selectedPaletteIndex !== null ? brand.palettes[brand.selectedPaletteIndex] : null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0A192F] via-[#0F2847] to-[#0A192F]">
      <nav className="container mx-auto px-6 py-5">
        <div className="flex items-center justify-between">
          <button
            onClick={() => {
              if (currentStep === 0) {
                setShowLeaveConfirm(true);
              } else {
                goBack();
              }
            }}
            className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
          >
            {currentStep === 0 ? <Home size={20} /> : <ArrowLeft size={20} />}
            <span className="text-sm font-medium">
              {currentStep === 0 ? 'Dashboard' : 'Back'}
            </span>
          </button>
          <h1 className="text-white font-bold text-lg font-['Montserrat'] hidden sm:block">Brand Studio</h1>
          <div className="w-20" />
        </div>
      </nav>

      <div className="container mx-auto px-6 pb-16">
        <BrandProgress
          currentStep={currentStep}
          totalSteps={5}
          stepLabels={STEP_LABELS}
        />

        <StepTransition stepKey={currentStep} direction={direction}>
          {currentStep === 0 && (
            <StepBusinessName
              businessDescription={brand.businessDescription}
              names={brand.names}
              selectedName={brand.selectedName}
              customName={customName}
              generating={generatingNames}
              businessIdeaContext={businessIdea ? `Business Idea: ${businessIdea.name} - ${businessIdea.description}` : undefined}
              onDescriptionChange={(desc) => setBrand({ ...brand, businessDescription: desc })}
              onGenerate={handleGenerateNames}
              onSelectName={handleSelectName}
              onCustomNameChange={setCustomName}
              onUseCustomName={handleUseCustomName}
              onNext={goForward}
            />
          )}

          {currentStep === 1 && (
            <StepPersonality
              selectedPersonalities={brand.personality}
              onToggle={handleTogglePersonality}
              onNext={handlePersonalityNext}
              onBack={goBack}
            />
          )}

          {currentStep === 2 && (
            <StepColorPalette
              palettes={brand.palettes}
              selectedIndex={brand.selectedPaletteIndex}
              loading={generatingPalettes}
              onSelectPalette={handleSelectPalette}
              onCustomizeColor={handleCustomizeColor}
              onRegenerate={() => {
                autoGeneratedPalettes.current = false;
                setBrand((prev) => prev ? { ...prev, palettes: [], selectedPaletteIndex: null } : null);
              }}
              onNext={goForward}
              onBack={goBack}
            />
          )}

          {currentStep === 3 && (
            <StepLogoGeneration
              concepts={brand.logoConcepts}
              selectedLogo={brand.selectedLogo}
              generating={generatingLogos}
              uploadedLogoUrl={brand.uploadedLogoUrl}
              uploadingLogo={uploadingLogo}
              onSelectLogo={handleSelectLogo}
              onRegenerate={(customDirection?: string) => {
                autoGeneratedLogos.current = false;
                setBrand((prev) => prev ? { ...prev, logoConcepts: [] } : null);
                setTimeout(() => handleGenerateLogos(customDirection), 100);
              }}
              onUpload={handleLogoUpload}
              onRemoveUpload={handleRemoveUpload}
              onNext={goForward}
              onBack={goBack}
            />
          )}

          {currentStep === 4 && (
            <StepBrandReveal
              businessName={brand.selectedName || ''}
              tagline={brand.tagline}
              personality={brand.personality}
              colors={{
                primary: palette?.primary || '#2979FF',
                secondary: palette?.secondary || '#0A192F',
                accent: palette?.accent || '#06D6A0',
              }}
              logoUrl={logoUrl}
              generatingTagline={generatingTagline}
              generatingGuide={generatingGuide}
              onRegenerateTagline={() => {
                autoGeneratedTagline.current = false;
                handleGenerateTagline();
              }}
              onDownloadGuide={handleDownloadGuide}
              onContinue={handleContinueToMessaging}
              onBack={goBack}
            />
          )}
        </StepTransition>
      </div>

      {showLeaveConfirm && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-[#0D2847] border border-white/10 rounded-2xl p-8 max-w-md w-full">
            <h3 className="text-xl font-bold text-white mb-3">Leave Brand Studio?</h3>
            <p className="text-gray-400 mb-6">Your progress will be saved.</p>
            <div className="flex gap-3">
              <button
                onClick={() => setShowLeaveConfirm(false)}
                className="flex-1 py-3 bg-white/5 border border-white/10 text-white rounded-xl font-semibold hover:bg-white/10 transition-all"
              >
                Stay
              </button>
              <button
                onClick={() => navigate('/dashboard')}
                className="flex-1 py-3 bg-[#2979FF] text-white rounded-xl font-semibold hover:bg-[#2979FF]/90 transition-all"
              >
                Leave
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
